from typing import Callable

# def cancel_animation_frame(): ...
# def clear_interval(): ...
# def clear_timeout(): ...
# def console(): ...
# def request_animation_frame(): ...
def set_interval(f: Callable[[], None], s: int) -> None: ...

# def set_loop_timeout(): ...
# def set_timeout(): ...
# def window(): ...
# def wrap(): ...
